# apiVersion: v1 
# kind: Pod 
# metadata: 
#  name: error-test 
# spec:
#  containers:
#  # Image pull backoff
# #  - name: nginx 
# #    image: ngindfdfadsfsaf --> solution -- nginx -- image pull backoff
#  #Crashloop backoff 
#  - name: almalinux 
#    image: almalinux:9
#    #command: ["sleep", "1000"] --> solution -- crashloop backoff

apiVersion: v1 
kind: Pod 
metadata: 
 name: errors 
spec: 
 containers: 
 - name: nginx 
   image: nginxxxxx #imagepull backoff
  #  - name: almalinux 
  #    image: almalinux:9 
     #command: ["sleep", "1000"] #crashloop backoff 