apiVersion: v1 
kind: Service 
metadata: 
 name: nginx-headless
 labels: 
  labels:
    app: nginx
    purpose: statefulset-demo 
spec: 
# if a service has clusterIP none then it is called as headless service
 clusterIP: None 
 selector:
  app: nginx
  purpose: statefulset-demo
 ports: 
 - protocol: TCP 
   port: 80 #service port 
   targetPort: 80 #container port 

---  

apiVersion: v1 
kind: Service 
metadata: 
 name: nginx 
spec: 
 selector:
  app: nginx
  purpose: statefulset-demo
 ports: 
 - protocol: TCP 
   port: 80 #service port 
   targetPort: 80 #container port 

---

apiVersion: apps/v1  
kind: StatefulSet 
metadata: 
 name: nginx 
spec: 
 selector: 
  matchLables:
   app: nginx 
   purpose: statefulset-demo # has to match .spec.template.metadata.labels
 replicas: 3 #by default 1 
 serviceName: "headless-nginx" # this should be head less service name
 template: 
  metadata: 
   labels: 
    app: nginx 
    purpose: statefulset-demo # has to match .spec.selector.matchLabels
  spec: 
   containers: 
   - name: nginx 
     image: nginx 
     ports: 
     - containerPort: 80 
       targetPort: 80
       #name: web 
     volumeMounts: 
     - name: web 
       mountPath: /usr/share/nginx/html

# This is PVC
  volumeClaimTemplates:
  - metadata:
      name: web 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi