apiVersion: v1 
kind: Service 
metadata: 
 name: nginx-headless
 labels: 
    app: nginx
    purpose: statefulset-demo 
spec: 
# if a service has clusterIP none then it is called as headless service
 clusterIP: None 
 selector:
  app: nginx
  purpose: statefulset-demo
 ports: 
 - protocol: TCP 
   port: 80 #service port 
   targetPort: 80 #container port 

---  

apiVersion: v1 
kind: Service 
metadata: 
 name: nginx 
spec: 
 selector:
  app: nginx
  purpose: statefulset-demo
 ports: 
 - protocol: TCP 
   port: 80 #service port 
   targetPort: 80 #container port 

---

apiVersion: apps/v1  
kind: StatefulSet 
metadata: 
 name: nginx 
spec: 
 selector: 
  matchLabels:
   app: nginx 
   purpose: statefulset-demo # has to match .spec.template.metadata.labels
 replicas: 3 #by default 1 
 serviceName: "nginx-headless" # this should be head less service name
 template: 
  metadata: 
   labels: 
    app: nginx 
    purpose: statefulset-demo # has to match .spec.selector.matchLabels
  spec: 
   containers: 
   - name: nginx 
     image: nginx 
     ports: 
     - conatinerPort: 80 
       name: web 
     volumeMounts: 
     - name: www
       mountPath: /usr/share/nginx/html

# This is PVC
 volumeClaimTemplates:
 - metadata:
    name: www 
   spec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "roboshop-ebs"
    resources:
      requests:
        storage: 1Gi